name: WakaTime Readme

on:
  push:
    branches:
      - master
  schedule:
    - cron: '10 * * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: True
          SHOW_LINES_OF_CODE: False
          SHOW_DAYS_OF_WEEK: True
          SHOW_LANGUAGE: True
          SHOW_PROJECTS: True
          SHOW_LANGUAGE_PER_REPO: False
          SHOW_SHORT_INFO: True
          SHOW_LOC_CHART: True
          IGNORED_REPOS: "NLPCC2021"
